# Generated by Django 5.1.4 on 2025-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('sobrenome', models.CharField(blank=True, max_length=256, null=True)),
                ('endereco', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
